CREATE DATABASE IF NOT EXISTS hitokuse DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON hitokuse.* TO 'shin'@'%' IDENTIFIED BY '1234567890';
USE hitokuse;

-- Time functions

DELIMITER //
 CREATE FUNCTION `now14`()
 RETURNS VARCHAR(14)
 MODIFIES SQL DATA
 DETERMINISTIC
 BEGIN
     DECLARE ret VARCHAR(14);
     SELECT DATE_FORMAT(NOW(), '%Y%m%d%H%i%s') INTO ret FROM DUAL;
     RETURN ret;
 END//
DELIMITER ;


DELIMITER //
 CREATE FUNCTION `priv14`(privSec BIGINT)
 RETURNS VARCHAR(14)
 MODIFIES SQL DATA
 DETERMINISTIC
 BEGIN
     DECLARE ret VARCHAR(14);
     SELECT DATE_FORMAT(DATE_ADD(now(), INTERVAL -privSec SECOND), '%Y%m%d%H%i%s') INTO ret FROM DUAL;
     RETURN ret;
 END//
DELIMITER ;

DELIMITER //
 CREATE FUNCTION `priv14_2`(t VARCHAR(14),privSec BIGINT)
 RETURNS VARCHAR(14)
 MODIFIES SQL DATA
 DETERMINISTIC
 BEGIN
     DECLARE ret VARCHAR(14);
     SELECT DATE_FORMAT(DATE_ADD(TIME_FORMAT(t, '%Y%m%d%H%i%s'), INTERVAL -privSec SECOND), '%Y%m%d%H%i%s') INTO ret FROM DUAL;
     RETURN ret;
 END//
DELIMITER ;


DELIMITER //
 CREATE FUNCTION `next14`(nextSec BIGINT)
 RETURNS VARCHAR(14)
 MODIFIES SQL DATA
 DETERMINISTIC
 BEGIN
     DECLARE ret VARCHAR(14);
     SELECT DATE_FORMAT(DATE_ADD(now(), INTERVAL nextSec SECOND), '%Y%m%d%H%i%s') INTO ret FROM DUAL;
     RETURN ret;
 END//
DELIMITER ;

DELIMITER //
 CREATE FUNCTION `str_time`(timeStr VARCHAR(14), formatType INT)
 RETURNS VARCHAR(20)
 MODIFIES SQL DATA
 DETERMINISTIC
 BEGIN
     DECLARE ret VARCHAR(20);
     SELECT 
     	CASE
     		WHEN formatType = 8
     		THEN CONCAT(SUBSTR(timeStr,1,4),'-',SUBSTR(timeStr,5,2),'-',SUBSTR(timeStr,7,2))
     		WHEN formatType = 12
     		THEN CONCAT(SUBSTR(timeStr,1,4),'-',SUBSTR(timeStr,5,2),'-',SUBSTR(timeStr,7,2),
     				' ',SUBSTR(timeStr,9,2),':',SUBSTR(timeStr,11,2))
     		WHEN formatType = 14
     		THEN CONCAT(SUBSTR(timeStr,1,4),'-',SUBSTR(timeStr,5,2),'-',SUBSTR(timeStr,7,2),
     				' ',SUBSTR(timeStr,9,2),':',SUBSTR(timeStr,11,2),':',SUBSTR(timeStr,13,2))
     	END
     INTO ret
     FROM DUAL;
     RETURN ret;
 END//
DELIMITER ;

DROP TABLE IF EXISTS Register;
CREATE TABLE IF NOT EXISTS Register (
	seq INTEGER PRIMARY KEY AUTO_INCREMENT,
	id VARCHAR(20),
	domain VARCHAR(100),
	recUsr VARCHAR(50),
	recTm VARCHAR(14)
);

CREATE INDEX RegisterIdx1 ON Register(id, domain);


DROP TABLE IF EXISTS Analytics;
CREATE TABLE IF NOT EXISTS Analytics (
	seq INTEGER,
	path VARCHAR(256),
	recTm VARCHAR(14)
);

CREATE INDEX AnalyticsIdx1 ON Analytics(seq, recTm);